name: Build and Publish Docker Image

on:
  push:
    branches:
      - dev
    paths:
      - '**/Dockerfile'
      - '**/docker-compose.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./docker/
          file: Dockerfile
          push: true
          tags: ghcr.io/p-society/gc-broadcast:latest
